version: '3.8'

services:
  wifi-login-gui:
    build:
      context: ..
      dockerfile: linux-install/Dockerfile
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${HOME}/.Xauthority:/root/.Xauthority:ro
    network_mode: host
    restart: unless-stopped

  wifi-login-headless:
    build:
      context: ..
      dockerfile: linux-install/Dockerfile
    command: ["python", "-m", "src.headless.service", "-c", "/config/headless.json"]
    volumes:
      - ./config:/config
    network_mode: host
    restart: unless-stopped 